### PR TITLE
chore(package): add `peerDependecies`

### LINKED ISSUE #117: Yarn 2 PnP stricter module resolution and mocha detection
Yarn 2 introduced new alternative stricter resolution system for modules - [Plug'n'Play](https://yarnpkg.com/features/pnp).

The problem: `bdd-lazy-var` does not have `mocha` as a dependency but still [relies](https://github.com/stalniy/bdd-lazy-var/blob/a367d375d9d6cd0c1238e91ddd575694d01a745d/lib/interface/index.js#L4) on it being resolvable during framework detection. PnP system does not allow that.

There is ["loose" mode](https://yarnpkg.com/features/pnp#pnp-loose-mode) that makes it work, but it still generates warnings about ambiguity and unsoundness of such require call.

### PR DESCRIPTION
**Pull request by vonagam**
Closes #117.

### CODE REVIEW

**Comment by stalniy** [comment]
Nice! Thank you!

**Comment by vonagam** [comment]
Is a release planned?

**Comment by stalniy** [comment]
Sorry for the delay . Will release this tomorrow

**Comment by vonagam** [comment]
No problem, thanks.

**Pull request merged**
